# Replace the text below to customize your site
site_name: This is my site!
site_description: Documentation for Job van der Knaap
site_author: Job van der Knaap
copyright: Copyright 2022 Job van der Knaap - Creative Commons Attribution Non Commercial

site_url: https://localhost:8000/
  
theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: light green
    accent: cyan
  font:
    # See available fonts at https://fonts.google.com/
    text: Arial
    code: Ubuntu Mono  
  logo: images/iot_house.svg
  favicon: images/iot_power.svg
  features:
    - navigation.instant 
    - content.code.annotate 
nav:
    - 'index.md'
    - 'Documentation' :
      - 'Feedback' : 'feedback.md'
      - 'Arduino/Wemos' : 'AW.md'
      - 'Web application' : 'web_application.md'
    - 'Product' :
      - 'Product Description' : 'product.md'
      - 'User Manual' : 'user_manual.md'
      - 'Architecture Overview' : 'architecture_overview.md'
    - 'Embedded Device' : 'embedded_device.md'
    - 'Web Application' :
      - 'Admin Manual' : 'admin_manual.md'
      - 'API Documentation' : 'api_documentation.md'
    - 'User Interaction' : 'user_interaction.md'
    - 'Physical Design' : 'physical_design.md'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.keys
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
